### ISSUE TITLE
Peer Code Review 1 - Darin Wellons

### ISSUE THREAD

**Issue by dwellons** [MNuenninghoff/NPCCreator#2]
|Item |Considerations| Comments/Suggestions<br/>|
|-------|---------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
||| Reviewer comments and suggestions go here. Each item should have *at least* one "kudos" and two suggestions for improvement|
|**Problem Statement**|1. Accurately describes project purpose<br> 2. Is professional and free of typos, slang, etc.<br> 3. Fully explains the problem and the solution<br> 4. Is understandable by the average person| - I think the problem statement does a good job explaining the purpose of the application and how it can be helpful to DM's. <br>- Your problem statement looks professional and I don't see any typo's. <br>- You do a good job explaining the terms that might be unfamiliar. <br> - I'm not sure if it would be helpful to define plot arc or if it is a well known part of the game.
|**Design Documentation**|1. Navigation/flow through the application is logical and easy to use. <br>2. The order in which values are displayed are logical and easy to understand/use <br>3. The order in which the form fields entered are logical and easy to understand/use<br>4. All data discussed/documented (problem statement, flow, db design, etc.) is represented on the screens | - I think the way your screens are designed and how the application will work will make it quick and easy to use and will let more of the game be played. <br>- The traits are displayed in the order you mentioned in the Masters Guide. I like that you will have the ability to "re roll" to choose a new trait if you want. <br>- The data mentioned in the problem statement as *MVP and in the user stories is all planned for. <br>- Would generating a villan require different traits than the ones that a generated NPC will be given, or would you be able to create a villan using the traits you have created already? <br>- I think it would be cool to have the theme of the application match the game in a way.
|**Data model/Database**|1. Everything on the screens and problem statement/flow is represented in the model <br> 2. There is at least one 1-to-many relationship.<br> 3. The model represents good database design <br>| - The information explainted in the problem statement is in the database.<br> - I think your database looks great and well structured, I was really impressed by it and how organized it looks. <br>- There are multiple one to many relationships. <br>- I think having an image associated with the traits would be a cool feature to implement in the future.
|**Code**|1. Proper Maven project structure is used<br> 2. a .gitignore file for IntelliJ Java projects has been implemented <br> 3. There is not any redundant or copy/paste code in the JSPs or classes<br> 4. Classes are appropriately-sized (no monster classes)<br> Property files are used appropriately: no hard-coded values <br> 5. Logging statements are used rather than System.out.println and printStackTrace.<br> 6. There are appropriate unit tests/code coverage.  7. No sensitive information is visible in the repository (secrets, passwords, etc). | - The code that you have written looks clean and well structured! <br>- I think like you mentioned, adding the database configuration files, logs etc. to your .gitignore file is a good idea to hide passwords, etc. <br>- None of the classes are huge and each serves its own purpose. <br>- The unit testing that you have for your InteractionTraits.java class is checking for CRUD <br>- The only little thing that stood out to me was that some of the comments have capitalization, punctuation and some don't.  

You have a great project idea and I think a lot of people are going to find this to be super useful. I also had a hard time finding suggestions, you have a solid start so far and everything you have is impressively clean and well-structured. You're ready for some JSP's and I'm excited to see how you make them, and the final product!

**Comment by pawaitemadisoncollege** [comment]
Hi @dwellons Thank you for your thorough review of @MNuenninghoff 's project so far. From the specificity of your comments and suggestions, it's clear you put in some time to thoroughly examine the project and you posed some thoughtful questions.  

I did a quick search for the word "print" and noticed a couple files where logging should be implemented instead, the Database class and the PropertiesLoader.

In reviewing this, I noticed there isn't a story for logging out - I think I missed this in my earlier review. It should be there to be thorough.
